project:
  type: website
  output-dir: docs
  resources: files

website:
  title: "Johané Nienkemper-Swanepoel"
  favicon: logo.png
  site-url: https://github.com/jnienk/jns-quarto
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Career and Awards
        href: education.qmd
      - text: Talks
        href: talks.qmd  
      - text: Publications
        href: publications.qmd  
      - text: Software
        href: software.qmd
    right:
      - icon: github
        href: https://github.com/jnienk/jns-quarto      

body-footer: | 
  Copyright:  Johane Nienkemper-Swanepoel, 2025

date-format: "D MMMM YYYY"

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true

