---
title: "Software"
---

## R packages

```{r}
#| echo: false
#| message: false
#| eval: false
library(tidyverse)
library(tsibble)
library(lubridate)
library(pkgsearch)
#remotes::install_github("robjhyndman/pkgmeta")
library(pkgmeta)

# Functions for getting downloads
find_cran_packages <- function(name) {
  pkgsearch::ps(name, size = 100) %>%
    filter(purrr::map_lgl(
      package_data, ~ grepl(name, .x$Author, fixed = TRUE)
    )) %>%
    select(package) %>%
    pull(package)
}

# Monthly download counts from packages in <x>
cran_downloads <- function(x) {
  # Compute monthly download counts
  down <- cranlogs::cran_downloads(x, from = "2023-01-01") %>%
    as_tibble() %>%
    mutate(month = tsibble::yearmonth(date)) %>%
    group_by(month) %>%
    summarise(count = sum(count), package = x)
  # Strip out initial zeros
  first_nonzero <- down %>%
    filter(count > 0) %>%
    head(1)
  if (NROW(first_nonzero) > 0) {
    filter(down, month >= first_nonzero$month)
  } else {
    first_nonzero
  }
}

packages <- c(    
  find_cran_packages("Johané Nienkemper-Swanepoel"),
  find_cran_packages("Johane Nienkemper-Swanepoel")
)

pkg_data <- pkgmeta:::get_meta_cran(packages, 
    include_downloads=TRUE) |>
    rename(released = first_download, last_update = date)

# Remove incorrect entries
pkg_data <- pkg_data |>
  filter(package != "MatTransMix")
save(pkg_data, file = "software.rda")
```

```{r}
#| message: false
#| eval: false
#| echo: false
#Download package hex stickers
# But avoid this because not all are in correct aspect ratio
#library(readr)
#library(glue)
#hex <- read_csv("hex.csv")
#download.file(hex$hexlink, 
#  destfile = glue("hex_images/{hex$package}.png"))
```

```{r}
#| echo: false
#| message: false
library(readr)
library(dplyr)
library(glue)
library(stringr)
suppressWarnings(suppressPackageStartupMessages({
  library(flextable)
  library(magick)
}))
hex <- read_csv("hex.csv") |>
  select(package, hexlink) |>
  rename(hex = hexlink)

load("software.rda")
pkg_data <- pkg_data |>
  #mutate(pkglink = glue("[{package}]({url})")) |>
  left_join(hex, by="package") |>
  #mutate(authors = str_replace(authors, "\\[aut, cre\\]", "")) |>
  #mutate(authors = str_replace(authors, "\\[aut, ctb\\]", "")) |>
  #mutate(authors = str_replace(authors, "\\[aut, ths\\]", "")) |>
  #mutate(authors = str_replace(authors, "\\[aut\\]//g", "")) |>
  #mutate(authors = str_replace(authors, "\\[ths\\]//g", "")) |>
  #mutate(authors = str_replace(authors, "\\[ctb\\]//g", "")) |>
  #mutate(authors = str_replace(authors, "\\[cph\\]", "")) |>
  #mutate(authors = str_replace(authors, "\n/g", "")) |>
  #mutate(authors = str_replace(authors, "\\([^)]*\\)//g", "")) |>
  #mutate(authors = str_replace(authors, "(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)", "")) |>
  arrange(desc(last_update))
pkg_data <- pkg_data |>
  mutate(hex = ifelse(is.na(hex), "hex_images/hex-none.png", hex))
pkg_tbl <- pkg_data |> 
  #select(pkglink, released, last_update, version, title, #authors, 
  #       downloads) |>
  select(package, last_update, released, version, title, downloads, url) |>
  flextable() |>   
    colformat_num(big.mark = ",", decimal.mark = ".") |>
    colformat_date(fmt_date = "%d/%m/%Y")
pkg_tbl <- compose(
  x = pkg_tbl,
  j = "package",
  value = as_paragraph(hyperlink_text(x=package, url=url, 
     props = officer::fp_text(color = "#dcaa5f")))) |>
  delete_columns(j = "url") 

#pkg_tbl <- colformat_image(x = pkg_tbl,
 
#                          i=1:nrow(pkg_data),
 
#                          j = "hex", width = 1, height = 1.156, 
 #                          na_str = "") 
pkg_tbl 
```

::: {style="font-size: 60%"}

*This page is automatically populated using `pkgsearch` with R with all time downloads.*

:::

## Shiny applications

- [Subset Multiple Correspondence Analysis](https://jnienk.shinyapps.io/sMCAbiplots/)
- [Embedded word Multiple Correspondence Analysis](https://muvisu.shinyapps.io/EmbeddedWordMCAbiplot/)